---
- name: Download AMD GPU-Pro driver
  include_tasks: amd-driver.yml

- name: Download and configure nbminer
  include_tasks: nbminer.yml

- name: Check to ensure atiflash archive is available
  stat: 
    path: "{{ atiflash_archive_source_path }}"
  register: atiflash_arch_exists

- name: Extract atiflash archive
  unarchive:
    remote_src: yes
    src: "{{ atiflash_archive_source_path }}"
    dest: /minebox
    extra_opts: "--strip-components=1"
    owner: "{{ minebox_svc_acct }}"
    group: "{{ minebox_svc_acct }}"
  when: atiflash_arch_exists == True