---
# - name: Download AMD GPU-Pro driver
#  include_tasks: amd-driver.yml

- name: Check to ensure atiflash archive is available
  stat: 
    path: "{{ crminer_atiflash_archive_source_path }}"
  register: atiflash_arch_exists

- name: Extract atiflash archive
  unarchive:
    remote_src: yes
    src: "{{ crminer_atiflash_archive_source_path }}"
    dest: /minebox
    extra_opts: "--strip-components=1"
    owner: "{{ crminer_svc_acct }}"
    group: "{{ crminer_svc_acct }}"
  when: atiflash_arch_exists.stat.exists == True