---
- name: Download teamredminer
  get_url: 
    url: "{{ ethminer_url }}"
    dest: /tmp/teamredminer.tgz

- name: Create teamredminer directory
  file:
    state: directory
    path: /minebox/teamredminer
    owner: "{{ minebox_svc_acct }}"
    group: "{{ minebox_svc_acct }}"
    mode: 0777

- name: Extract teamredminer tarball
  unarchive:
    remote_src: yes
    src: /tmp/teamredminer.tgz
    dest: /minebox/teamredminer
    extra_opts: "--strip-components=1"
    owner: "{{ minebox_svc_acct }}"
    group: "{{ minebox_svc_acct }}"