---
- name: Download ethminer
  get_url: 
    url: "{{ ethminer_url }}"
    dest: /tmp/ethminer.tgz

- name: Extract ethminer tarball
  unarchive:
    remote_src: yes
    src: /tmp/ethminer.tgz
    dest: /minebox/ethminer
    extra_opts: "--strip-components=1"
    owner: "{{ minebox_svc_acct }}"
    group: "{{ minebox_svc_acct }}"

- name: Create ethminer startup script
  template:
    src: start-miner.sh.j2
    dest: /minebox/start-miner.sh
    mode: 0770
    owner: "{{ minebox_svc_acct }}"
    group: "{{ minebox_svc_acct }}"