---
- name: Disable apt auto upgrades
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '^APT::Periodic::Unattended-Upgrade "0";'
    line: APT::Periodic::Unattended-Upgrade "1";

- name: Configure grub
  include_tasks: grub.yml

- name: rc.local
  file:
    path: /etc/rc.local
    state: touch
    mode: 0744
    access_time: preserve
    modification_time: preserve

- name: Update /etc/skel/.bashrc
  lineinfile:
    path: /etc/skel/.bashrc
    line: export DISPLAY=:0
  notify: Update XDM

- name: Configure serice account
  import_tasks: service_account.yml

- name: Create minebox directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ minebox_svc_acct }}"
    group: "{{ minebox_svc_acct }}"
    mode: 0777
  loop: "{{ minebox_folders }}"

- name: Install common packages
  apt:
    update_cache: yes
    pkg: "{{ minebox_pkgs.common }}"

- name: Install docker
  import_role:
    name: docker

- name: AMD GPU configuration
  include_tasks: amd-main.yml
  when: gpu_arch == 'amd'

- name: NVidia GPU configuration
  include_tasks: nvidia-main.yml
  when: gpu_arch == 'nvidia'

- name: Download miners
  include: miners.yml

- name: Create miner startup script
  template:
    src: start-miner.sh.j2
    dest: /minebox/start-miner.sh
    mode: 0770
    owner: "{{ minebox_svc_acct }}"
    group: "{{ minebox_svc_acct }}"
  when: mining_type == 'script'

- name: Configure crontab for script-based mining
  include_tasks: cronmine.yml
  when: mining_type == 'script'
