---
- name: Download and configure nbminer
  include_tasks: miner_nbminer.yml

- name: Download and configure nanominer
  include_tasks: miner_nanominer.yml

- name: Download teamreadminer
  import_tasks: miner_teamredminer.yml

- name: Download ethminer
  import_tasks: miner_ethminer.yml

- name: Copy phoenixminer
  include_tasks: miner_phoenixminer.yml

- name: Copy lolMiner
  include_tasks: miner_lolminer.yml