---
- name: Create teamredminer directory
  file:
    state: directory
    path: "{{item}}"
    owner: "{{ crminer_svc_acct }}"
    group: "{{ crminer_svc_acct }}"
    mode: 0777
  loop:
    - /minebox/teamredminer
    - /minebox/teamredminer/bin

- name: Download teamredminer
  get_url: 
    url: "https://github.com/todxx/teamredminer/releases/download/{{ crminer_teamredminer_version }}/teamredminer-v{{ crminer_teamredminer_version }}-linux.tgz"
    dest: /minebox/teamredminer

- name: Extract teamredminer tarball
  unarchive:
    remote_src: yes
    src: "/minebox/teamredminer/teamredminer-v{{ crminer_teamredminer_version }}-linux.tgz"
    dest: /minebox/teamredminer/bin
    extra_opts: "--strip-components=1"
    owner: "{{ crminer_svc_acct }}"
    group: "{{ crminer_svc_acct }}"

- name: Create teamredminer startup script
  template:
    src: start-teamredminer.sh.j2
    dest: /minebox/teamredminer/start-teamredminer.sh
    mode: 0770
    owner: "{{ crminer_svc_acct }}"
    group: "{{ crminer_svc_acct }}"