---
- name: Create lolminer directory
  file:
    state: directory
    path: "{{item}}"
    owner: "{{ crminer_svc_acct }}"
    group: "{{ crminer_svc_acct }}"
    mode: 0777
  loop:
    - /minebox/lolminer
    - /minebox/lolminer/bin

- name: Download lolminer
  get_url: 
    url: "https://github.com/Lolliedieb/lolMiner-releases/releases/download/{{ crminer_lolminer_version }}/lolMiner_v{{ crminer_lolminer_version }}_Lin64.tar.gz"
    dest: /minebox/lolminer

- name: Extract lolminer tarball
  unarchive:
    remote_src: yes
    src: "/minebox/lolminer/lolMiner_v{{ crminer_lolminer_version }}_Lin64.tar.gz"
    dest: /minebox/lolminer/bin
    extra_opts: "--strip-components=1"
    owner: "{{ crminer_svc_acct }}"
    group: "{{ crminer_svc_acct }}"

- name: Create lolminer startup script
  template:
    src: start-lolminer.sh.j2
    dest: /minebox/lolminer/start-lolminer.sh
    mode: 0770
    owner: "{{ crminer_svc_acct }}"
    group: "{{ crminer_svc_acct }}"