---
  - name: Create nanominer directory
    file:
      state: directory
      path: "{{item}}"
      owner: "{{ crminer_svc_acct }}"
      group: "{{ crminer_svc_acct }}"
      mode: 0777
    loop:
      - /minebox/nanominer
      - /minebox/nanominer/bin
  
  - name: Download nanominer
    get_url: 
      url: "https://github.com/nanopool/nanominer/releases/download/v{{ crminer_nanominer_version }}/nanominer-linux-{{ crminer_nanominer_version }}.tar.gz"
      dest: /minebox/nanominer
  
  - name: Extract nanominer tarball
    unarchive:
      remote_src: yes
      src: "/minebox/nanominer/nanominer-linux-{{ crminer_nanominer_version }}.tar.gz"
      dest: /minebox/nanominer/bin
      extra_opts: "--strip-components=1"
      owner: "{{ crminer_svc_acct }}"
      group: "{{ crminer_svc_acct }}"
  
  - name: Create nanominer config file
    template:
      src: nanominer.ini.j2
      dest: /minebox/nanominer/nanominer.ini
      mode: 0770
      owner: "{{ crminer_svc_acct }}"
      group: "{{ crminer_svc_acct }}"