---
- name: Check to ensure phoenixminer archive is available
  stat: 
    path: "{{ crminer_phoenixminer_archive_source_path }}"
  register: pm_arch_exists

- name: Create phoenixminer directory
  file:
    state: directory
    path: /minebox/phoenixminer
    owner: "{{ crminer_svc_acct }}"
    group: "{{ crminer_svc_acct }}"
    mode: 0777
  when: pm_arch_exists.stat.exists

- name: Extract phoenixminer tarball
  unarchive:
    remote_src: yes
    src: "{{ crminer_phoenixminer_archive_source_path }}"
    dest: /minebox/phoenixminer
    extra_opts: "--strip-components=1"
    owner: "{{ crminer_svc_acct }}"
    group: "{{ crminer_svc_acct }}"
  when: pm_arch_exists.stat.exists

- name: Create Phoenix Miner startup script
  template:
    src: start-phoenix.sh.j2
    dest: /minebox/phoenixminer/start-phoenix.sh
    mode: 0770
    owner: "{{ crminer_svc_acct }}"
    group: "{{ crminer_svc_acct }}"