---
- name: Download ethminer
  get_url: 
    url: "{{ ethminer_url }}"
    dest: /tmp/ethminer.tgz

- name: Create ethminer directory
  file:
    state: directory
    path: /minebox/ethminer
    owner: "{{ minebox_svc_acct }}"
    group: "{{ minebox_svc_acct }}"
    mode: 0777

- name: Extract ethminer tarball
  unarchive:
    remote_src: yes
    src: /tmp/ethminer.tgz
    dest: /minebox/ethminer
    extra_opts: "--strip-components=1"
    owner: "{{ minebox_svc_acct }}"
    group: "{{ minebox_svc_acct }}"