---
- name: Create minebox user
  user:
    name: "{{ minebox_svc_acct }}"
    shell: /bin/bash #/usr/bin/zsh
    groups: video
    append: yes

- name: Ensure .bashrc exists
  file:
    path: "/home/{{ minebox_svc_acct }}/.bashrc"
    state: touch
    access_time: preserve
    modification_time: preserve
    mode: 0774
    owner: "{{ minebox_svc_acct }}"
    group: "{{ minebox_svc_acct }}"

- name: Update service account .bashrc
  lineinfile:
    path: "/home/{{ minebox_svc_acct }}/.bashrc"
    line: export DISPLAY=:0
  notify: Update XDM

- name: Generate .screenrc for service account
  template:
    src: screenrc.j2
    dest: /home/{{ minebox_svc_acct }}/.screenrc
    mode: 0774
    owner: "{{ minebox_svc_acct }}"
    group: "{{ minebox_svc_acct }}"
  when: gpu_arch == 'nvidia'

- name: Run tmux at login
  lineinfile:
    path: "/home/{{ minebox_svc_acct }}/.profile"
    line: tmux attach-session -t $SESSION:0

- name: Allow service account group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%"{{ minebox_svc_acct }}"'
    line: '%"{{ minebox_svc_acct }}" ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'