---
- name: Create minebox user
  user:
    name: "{{ minebox_svc_acct }}"
    shell: /usr/bin/zsh
    groups: sudo,video
    append: yes

- name: Update service account .bashrc
  lineinfile:
    path: /home/miner/.bashrc
    line: export DISPLAY=:0
  notify: Update XDM

- name: Generate .screenrc for service account
  template:
    src: screenrc.j2
    dest: /home/{{ minebox_svc_acct }}/.screenrc
    mode: 0774
    owner: "{{ minebox_svc_acct }}"
    group: "{{ minebox_svc_acct }}"
